# Generated by Django 5.2.5 on 2025-09-03 20:31

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='कार्यक्रम नाम')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='विवरण')),
                ('category', models.CharField(max_length=100, verbose_name='श्रेणी')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='जिला')),
                ('venue', models.CharField(max_length=200, verbose_name='स्थान')),
                ('event_date', models.DateTimeField(verbose_name='कार्यक्रम तिथि')),
                ('registration_deadline', models.DateTimeField(verbose_name='पंजीकरण अंतिम तिथि')),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='पंजीकरण शुल्क')),
                ('max_participants', models.PositiveIntegerField(default=100, verbose_name='अधिकतम प्रतिभागी')),
                ('is_published', models.BooleanField(default=True, verbose_name='प्रकाशित')),
                ('is_featured', models.BooleanField(default=False, verbose_name='मुख्य कार्यक्रम')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'कार्यक्रम',
                'verbose_name_plural': 'कार्यक्रम',
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(max_length=10, verbose_name='राज्य कोड')),
                ('districts', models.JSONField(blank=True, default=list, verbose_name='जिले')),
                ('is_state_approver', models.BooleanField(default=False, verbose_name='राज्य अप्रूवर')),
                ('is_district_approver', models.BooleanField(default=False, verbose_name='जिला अप्रूवर')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'अप्रूवल यूजर',
                'verbose_name_plural': 'अप्रूवल यूजर',
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_images/', verbose_name='छवि')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='कैप्शन')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.event')),
            ],
            options={
                'verbose_name': 'कार्यक्रम छवि',
                'verbose_name_plural': 'कार्यक्रम छवियां',
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_type', models.CharField(choices=[('participant', 'प्रतिभागी'), ('volunteer', 'समयदानी कार्यकर्ता')], default='participant', max_length=20, verbose_name='पंजीकरण प्रकार')),
                ('registration_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('full_name', models.CharField(max_length=100, verbose_name='नाम')),
                ('phone', models.CharField(max_length=15, verbose_name='मोबाइल नं.')),
                ('email', models.EmailField(max_length=254, verbose_name='ईमेल')),
                ('date_of_birth', models.DateField(verbose_name='जन्म तिथि')),
                ('gender', models.CharField(choices=[('M', 'पुरुष'), ('F', 'महिला'), ('O', 'अन्य')], max_length=1, verbose_name='लिंग')),
                ('transport_mode', models.CharField(choices=[('car', 'कार'), ('bike', 'बाइक'), ('bus', 'बस'), ('train', 'ट्रेन'), ('auto', 'ऑटो/टैक्सी'), ('walking', 'पैदल'), ('other', 'अन्य')], max_length=20, verbose_name='आप किस माध्यम से कार्यक्रम स्थल तक पहुंचेंगे?')),
                ('vehicle_number', models.CharField(blank=True, max_length=20, verbose_name='वाहन नंबर')),
                ('previous_shivir', models.BooleanField(default=False, verbose_name='क्या आप शांतिकुंज या अन्य शाखाओं में पहले कोई शिविर कर चुके हैं?')),
                ('education', models.CharField(choices=[('high_school', 'हाई स्कूल (10वीं)'), ('intermediate', 'इंटरमीडिएट (12वीं)'), ('graduation', 'स्नातक (Graduation – BA/BSc/BCom)'), ('graduation_tech', 'स्नातक तकनीकी (B.Tech/BCA/BBA)'), ('post_graduation', 'परास्नातक (Post Graduation – MA/MSc/MCom)'), ('post_graduation_tech', 'परास्नातक तकनीकी (M.Tech/MBA/MCA)'), ('iti_diploma', 'आईटीआई / डिप्लोमा'), ('sanskrit', 'संस्कृत शिक्षा (शास्त्री / आचार्य)')], max_length=50, verbose_name='शैक्षणिक योग्यता')),
                ('occupation', models.CharField(blank=True, max_length=100, null=True, verbose_name='व्यवसाय')),
                ('special_skills', models.JSONField(blank=True, default=list, verbose_name='विशेष कौशल')),
                ('special_skills_other', models.TextField(blank=True, verbose_name='अन्य विशेष कौशल')),
                ('village_taluka', models.CharField(max_length=100, verbose_name='गांव/तालुका')),
                ('country', models.CharField(blank=True, default='India', max_length=64, verbose_name='देश')),
                ('state', models.CharField(max_length=64, verbose_name='राज्य')),
                ('city', models.CharField(max_length=64, verbose_name='जनपद/जिला')),
                ('arrival_date', models.CharField(choices=[('2025-10-25', '25 अक्टूबर 2025'), ('2025-10-26', '26 अक्टूबर 2025')], max_length=10, verbose_name='आगमन तिथि')),
                ('interested_in_volunteering', models.BooleanField(default=False, verbose_name='क्या आप किसी विशेष टीम/सेवा में योगदान देना चाहते हैं?')),
                ('volunteering_details', models.TextField(blank=True, verbose_name='आप कैसे योगदान देना चाहते हैं?')),
                ('selected_campaigns', models.JSONField(default=list, verbose_name='चयनित अभियान')),
                ('approval_status', models.CharField(choices=[('pending', 'प्रतीक्षारत'), ('level1_approved', 'स्तर 1 अप्रूव'), ('approved', 'अप्रूव'), ('rejected', 'अस्वीकृत')], default='pending', max_length=20, verbose_name='अप्रूवल स्थिति')),
                ('level1_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='स्तर 1 अप्रूवल समय')),
                ('final_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='अंतिम अप्रूवल समय')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='अस्वीकृति कारण')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='पुष्ट')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.BooleanField(default=False, verbose_name='भुगतान स्थिति')),
                ('email_sent', models.BooleanField(default=False, verbose_name='ईमेल भेजा गया')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
                ('final_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_approvals', to=settings.AUTH_USER_MODEL, verbose_name='अंतिम अप्रूवर')),
                ('level1_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level1_approvals', to=settings.AUTH_USER_MODEL, verbose_name='स्तर 1 अप्रूवर')),
            ],
            options={
                'verbose_name': 'पंजीकरण',
                'verbose_name_plural': 'पंजीकरण',
                'ordering': ['-registration_date'],
            },
        ),
    ]
