# Generated by Django 5.2.3 on 2025-07-11 05:37

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='कार्यक्रम नाम')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='विवरण')),
                ('category', models.CharField(max_length=100, verbose_name='श्रेणी')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='जिला')),
                ('venue', models.CharField(max_length=200, verbose_name='स्थान')),
                ('event_date', models.DateTimeField(verbose_name='कार्यक्रम तिथि')),
                ('registration_deadline', models.DateTimeField(verbose_name='पंजीकरण अंतिम तिथि')),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='पंजीकरण शुल्क')),
                ('max_participants', models.PositiveIntegerField(default=100, verbose_name='अधिकतम प्रतिभागी')),
                ('is_published', models.BooleanField(default=True, verbose_name='प्रकाशित')),
                ('is_featured', models.BooleanField(default=False, verbose_name='मुख्य कार्यक्रम')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'कार्यक्रम',
                'verbose_name_plural': 'कार्यक्रम',
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_images/', verbose_name='छवि')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='कैप्शन')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.event')),
            ],
            options={
                'verbose_name': 'कार्यक्रम छवि',
                'verbose_name_plural': 'कार्यक्रम छवियां',
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=100, verbose_name='नाम')),
                ('phone', models.CharField(max_length=15, verbose_name='मोबाइल नं.')),
                ('email', models.EmailField(max_length=254, verbose_name='ईमेल')),
                ('date_of_birth', models.DateField(verbose_name='जन्म तिथि')),
                ('gender', models.CharField(choices=[('M', 'पुरुष'), ('F', 'महिला'), ('O', 'अन्य')], max_length=1, verbose_name='लिंग')),
                ('bringing_vehicle', models.BooleanField(default=False, verbose_name='क्या आप वाहन ला रहे हैं?')),
                ('vehicle_number', models.CharField(blank=True, max_length=20, verbose_name='वाहन नंबर')),
                ('previous_shivir', models.BooleanField(default=False, verbose_name='क्या आप शांतिकुंज या अन्य शाखाओं में पहले कोई शिविर कर चुके हैं?')),
                ('education', models.CharField(choices=[('high_school', 'हाई स्कूल (10वीं)'), ('intermediate', 'इंटरमीडिएट (12वीं)'), ('graduation', 'स्नातक (Graduation – BA/BSc/BCom)'), ('graduation_tech', 'स्नातक तकनीकी (B.Tech/BCA/BBA)'), ('post_graduation', 'परास्नातक (Post Graduation – MA/MSc/MCom)'), ('post_graduation_tech', 'परास्नातक तकनीकी (M.Tech/MBA/MCA)'), ('iti_diploma', 'आईटीआई / डिप्लोमा'), ('sanskrit', 'संस्कृत शिक्षा (शास्त्री / आचार्य)')], max_length=50, verbose_name='शैक्षणिक योग्यता')),
                ('occupation', models.CharField(blank=True, max_length=100, null=True, verbose_name='व्यवसाय')),
                ('special_skills', models.TextField(blank=True, verbose_name='विशेष कौशल')),
                ('village_taluka', models.CharField(max_length=100, verbose_name='गांव/तालुका')),
                ('country', models.CharField(default='India', max_length=64, verbose_name='देश')),
                ('state', models.CharField(max_length=64, verbose_name='राज्य')),
                ('city', models.CharField(max_length=64, verbose_name='जनपद/जिला')),
                ('arrival_date', models.DateField(verbose_name='आगमन तिथि')),
                ('departure_date', models.DateField(verbose_name='प्रस्थान तिथि')),
                ('interested_in_volunteering', models.BooleanField(default=False, verbose_name='क्या आप किसी विशेष टीम/सेवा में योगदान देना चाहते हैं?')),
                ('volunteering_details', models.TextField(blank=True, verbose_name='आप कैसे योगदान देना चाहते हैं?')),
                ('selected_campaigns', models.JSONField(default=list, verbose_name='चयनित अभियान')),
                ('is_confirmed', models.BooleanField(default=True, verbose_name='पुष्ट')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.BooleanField(default=False, verbose_name='भुगतान स्थिति')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
            ],
            options={
                'verbose_name': 'पंजीकरण',
                'verbose_name_plural': 'पंजीकरण',
                'ordering': ['-registration_date'],
            },
        ),
    ]
