# Generated by Django 5.2.3 on 2025-07-11 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'प्रतीक्षारत'), ('level1_approved', 'स्तर 1 अप्रूव'), ('approved', 'अप्रूव'), ('rejected', 'अस्वीकृत')], default='pending', max_length=20, verbose_name='अप्रूवल स्थिति'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='final_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='अंतिम अप्रूवल समय'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='final_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_approvals', to=settings.AUTH_USER_MODEL, verbose_name='अंतिम अप्रूवर'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='level1_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='स्तर 1 अप्रूवल समय'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='level1_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level1_approvals', to=settings.AUTH_USER_MODEL, verbose_name='स्तर 1 अप्रूवर'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='अस्वीकृति कारण'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='पुष्ट'),
        ),
        migrations.CreateModel(
            name='ApprovalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(max_length=10, verbose_name='राज्य कोड')),
                ('districts', models.JSONField(blank=True, default=list, verbose_name='जिले')),
                ('is_state_approver', models.BooleanField(default=False, verbose_name='राज्य अप्रूवर')),
                ('is_district_approver', models.BooleanField(default=False, verbose_name='जिला अप्रूवर')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'अप्रूवल यूजर',
                'verbose_name_plural': 'अप्रूवल यूजर',
            },
        ),
    ]
