# Generated by Django 5.2.5 on 2025-09-10 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_add_registration_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsibilityOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='जिम्मेदारी नाम')),
                ('is_active', models.BooleanField(default=True, verbose_name='सक्रिय')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'जिम्मेदारी विकल्प',
                'verbose_name_plural': 'जिम्मेदारी विकल्प',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='registration_type',
            field=models.CharField(choices=[('participant', 'प्रतिभागी'), ('volunteer', 'समयदानी कार्यकर्ता'), ('organization_representative', 'संगठन प्रतिनिधि')], default='participant', max_length=30, verbose_name='पंजीकरण प्रकार'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='responsibility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.responsibilityoption', verbose_name='जिम्मेदारी'),
        ),
    ]
