# Generated by Django 5.2.5 on 2025-09-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_responsibilityoption_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsibilityoption',
            options={'ordering': ['order', 'name'], 'verbose_name': 'जिम्मेदारी विकल्प', 'verbose_name_plural': 'जिम्मेदारी विकल्प'},
        ),
        migrations.AddField(
            model_name='responsibilityoption',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='क्रम'),
        ),
    ]
