# Generated by Django 5.2.5 on 2025-09-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_responsibilityoption_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VibhagOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='विभाग नाम')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='क्रम')),
                ('is_active', models.BooleanField(default=True, verbose_name='सक्रिय')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'विभाग विकल्प',
                'verbose_name_plural': 'विभाग विकल्प',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='selected_vibhags',
            field=models.JSONField(blank=True, default=list, verbose_name='चयनित विभाग'),
        ),
    ]
