# Generated by Django 5.2.3 on 2025-07-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_eventregistration_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='special_skills_other',
            field=models.TextField(blank=True, verbose_name='अन्य विशेष कौशल'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='special_skills',
            field=models.JSONField(blank=True, default=list, verbose_name='विशेष कौशल'),
        ),
    ]
