# Generated by Django 5.2.5 on 2025-09-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_add_vibhag_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='volunteer_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='समयदान समाप्ति तिथि'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='volunteer_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='समयदान प्रारंभ तिथि'),
        ),
    ]
