# Generated by Django 5.2.5 on 2025-09-18 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_add_volunteer_duration_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UpZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='उपजोन नाम')),
                ('districts', models.JSONField(default=list, verbose_name='जिले')),
                ('is_active', models.BooleanField(default=True, verbose_name='सक्रिय')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'उपजोन',
                'verbose_name_plural': 'उपजोन',
            },
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='level1_approved_at',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='level1_approver',
        ),
        migrations.AddField(
            model_name='approvaluser',
            name='is_upzone_approver',
            field=models.BooleanField(default=False, verbose_name='उपजोन अप्रूवर'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='district_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='जिला अप्रूवल समय'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='district_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_approvals', to=settings.AUTH_USER_MODEL, verbose_name='जिला अप्रूवर'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='upzone_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='उपजोन अप्रूवल समय'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='upzone_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upzone_approvals', to=settings.AUTH_USER_MODEL, verbose_name='उपजोन अप्रूवर'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'प्रतीक्षारत'), ('district_approved', 'जिला अप्रूव'), ('upzone_approved', 'उपजोन अप्रूव'), ('approved', 'अप्रूव'), ('rejected', 'अस्वीकृत')], default='pending', max_length=20, verbose_name='अप्रूवल स्थिति'),
        ),
        migrations.AddField(
            model_name='approvaluser',
            name='upzone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.upzone', verbose_name='उपजोन'),
        ),
    ]
