# Generated by Django 5.2.3 on 2025-07-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventregistration_special_skills_other_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='bringing_vehicle',
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='transport_mode',
            field=models.CharField(choices=[('car', 'कार'), ('bike', 'बाइक'), ('bus', 'बस'), ('train', 'ट्रेन'), ('auto', 'ऑटो/टैक्सी'), ('walking', 'पैदल'), ('other', 'अन्य')], default=1, max_length=20, verbose_name='आप किस माध्यम से कार्यक्रम स्थल तक पहुंचेंगे?'),
            preserve_default=False,
        ),
    ]
