# Generated by Django 5.2.5 on 2025-09-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_upzone_remove_eventregistration_level1_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='aadhar_back',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='आधार पीछे'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='aadhar_front',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='आधार आगे'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='aadhar_full',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='पूरा आधार'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='aadhar_upload_type',
            field=models.CharField(blank=True, choices=[('full', 'पूरा आधार'), ('separate', 'अलग-अलग (आगे-पीछे)')], max_length=20, null=True, verbose_name='आधार अपलोड प्रकार'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='पासपोर्ट फोटो'),
        ),
    ]
