# Generated by Django 5.2.3 on 2025-07-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_eventregistration_bringing_vehicle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='registration_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
