# Generated by Django 5.2.3 on 2025-07-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_eventregistration_registration_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='departure_date',
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='arrival_date',
            field=models.CharField(choices=[('2025-10-25', '25 अक्टूबर 2025'), ('2025-10-26', '26 अक्टूबर 2025'), ('2025-10-27', '27 अक्टूबर 2025')], max_length=10, verbose_name='आगमन तिथि'),
        ),
    ]
