# Generated by Django 5.2.5 on 2025-09-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_add_document_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='aadhar_back',
            field=models.URLField(blank=True, null=True, verbose_name='आधार पीछे'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='aadhar_front',
            field=models.URLField(blank=True, null=True, verbose_name='आधार आगे'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='aadhar_full',
            field=models.URLField(blank=True, null=True, verbose_name='पूरा आधार'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='passport_photo',
            field=models.URLField(blank=True, null=True, verbose_name='पासपोर्ट फोटो'),
        ),
    ]
