# Generated by Django 5.2.5 on 2025-09-23 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_country_alter_eventregistration_city_state_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventregistration',
            options={'ordering': ['-registration_date'], 'permissions': [('view_all_eventregistration', 'Can view all registrations')], 'verbose_name': 'पंजीकरण', 'verbose_name_plural': 'पंजीकरण'},
        ),
    ]
