# Generated by Django 5.2.5 on 2025-09-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_eventregistration_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaluser',
            name='is_super_approver',
            field=models.BooleanField(default=False, verbose_name='सुपर अप्रूवर (सभी स्तर)'),
        ),
    ]
