# Generated by Django 5.2.5 on 2025-09-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_approvaluser_is_super_approver'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100, verbose_name='राज्य नाम')),
                ('state_code', models.CharField(max_length=10, verbose_name='राज्य कोड')),
                ('district_name', models.CharField(max_length=100, verbose_name='जिला नाम')),
                ('is_active', models.BooleanField(default=True, verbose_name='सक्रिय')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'राज्य-जिला',
                'verbose_name_plural': 'राज्य-जिले',
                'ordering': ['state_name', 'district_name'],
                'unique_together': {('state_code', 'district_name')},
            },
        ),
    ]
