# Generated by Django 5.2.5 on 2025-09-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_add_state_district_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='चेतावनी शीर्षक')),
                ('message', models.TextField(verbose_name='चेतावनी संदेश')),
                ('is_active', models.BooleanField(default=True, verbose_name='सक्रिय')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'साइट चेतावनी',
                'verbose_name_plural': 'साइट चेतावनी',
                'ordering': ['-created_at'],
            },
        ),
    ]
