# Generated by Django 5.2.5 on 2025-10-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_add_site_warning'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaluser',
            name='allowed_registration_types',
            field=models.JSONField(blank=True, default=list, verbose_name='अनुमतित पंजीकरण प्रकार'),
        ),
    ]
