# Generated by Django 5.2.5 on 2025-10-02 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_add_registration_type_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='अस्वीकृति समय'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejections', to=settings.AUTH_USER_MODEL, verbose_name='अस्वीकृत करने वाला'),
        ),
    ]
